[package]
name = "bartender"
version = "0.1.0"
edition = "2021"

[dependencies]
dbus = "0.9.7"
i3ipc = "0.10.1"
lazy_static = "1.4.0"
libpulse-binding = "2.28.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.104"
